name: deepfakedetector
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.5.0

  # Audio & Files
  flutter_sound: ^9.2.13
  file_picker: ^8.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  path: ^1.9.0


  # API
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
